### PR TITLE
Consolidate extras into reference, and transfer cluster exercise into Ep. 13

### LINKED ISSUE #256: consolidate extras
At present, the Extras menu lists 7 items, many of which are populated with just one paragraph. Consolidate:

- [x] `_extras/discuss.md` (FAQ) into `reference.md`
- [x] `_extras/guide.md` (cluster roleplay) into the callout in `_episodes/13-scheduler.md`
- [x] Migrate symbol error from `_extras/guide.md` into `reference.md`

### PR DESCRIPTION
**Pull request by tkphd**
Closes #256.

### CODE REVIEW

**Comment by psteinb** [comment]
@tkphd 2 failing and 4 cancelled checks. Can you have a look?

**Comment by tkphd** [comment]
Yep, on it.

**Comment by tkphd** [comment]
Fixt.

**Review by reid-a — APPROVED** [review]
This looks good. One minor addition (not a big enough deal to block approval) is to note, in the quick reference section, that the SchedMD folks who supply the PDF are in fact the developers of SLURM, it's not some rando's blog post. Contrasts with the Iowa State Torque/PBS link, I think they are not the developers of that system?

**Comment by tkphd** [comment]
Indeed, it is so! Couldn't find an equivalent cheat sheet on the Adaptive Computing website, so, decided to link to some reasonably decent looking university resources. I think it's digging into the weeds a bit much to make note of the provenance of our links, but I could, if you feel strongly.

**Pull request merged**
