### PR TITLE
removing myself from the list of maintainers

### PR DESCRIPTION
**Pull request by psteinb**
it was fun as long as it lasted

### CODE REVIEW

**Review by annajiat — APPROVED** [review]

**Comment by tobyhodges** [comment]
Thank you for all your work on this project @psteinb You have contributed something that has helped a lot of people and will go on to help many more.

**Comment by reid-a** [comment]
Peter -- 

Let me add my thanks to you for giving this effort such a strong start. What we're doing going forward would have been impossible without your contributions.

I'm not sure how much experience you have with project management, but from my own experience, i can tell you that starting a project, and being able to hand it off to successors and have it continue to thrive is rare -- so many good projects remain dependent on their originators, because they fail to nurture a community, or because the founder tries to preserve their vision by overzealous gate-keeping. A successful hand-off is a rare and beautiful thing, we'll do our best to keep it going!

**Comment by psteinb** [comment]
Thank you for your kind words @tobyhodges and @reid-a. They mean a lot to me. I'll try to stay connected.

**Comment by annajiat** [comment]
Thank you @psteinb, even though I am relatively new here, I have found you to be an inspiration not only for your great contributions but also for trying to stay connected in the long run. That's another example you have set for the contributors.

**Comment by psteinb** [comment]
Thank you @annajiat - that is very kind of you. I appreciate that.

**Comment by tkphd** [comment]
Big Feels on this one, Peter. Thank you so much for investing all that you have to create great lesson materials, bring in new project members, and foster our growing community. I hope that after some time resettling, you can return to HPC Carpentry in some way. Until then, *gute reise!*

**Comment by Sabryr** [comment]
This is surprising news, @psteinb was the reason I moved out the silo for a community driven HPC training. I did not follow the full details, I guess you will still be involved, but not as a maintainer.

**Comment by mikerenfro** [comment]
Late to the party here. Sufice to say I don't think we'd have an hpc-intro if there hadn't already been an hpc-in-a-day. Thanks.

**Comment by psteinb** [comment]
Dear @tkphd, thanks for these kind words - they mean a lot to me. I sure will appear in a couple of issues/PRs here and there. I need some help to conduct a similar hand-off process with https://github.com/hpc-carpentry/hpc-parallel-novice

**Comment by psteinb** [comment]
Dear @Sabryr it is awesome to read your comment. I am grateful for having had a positive impact. Your contributions were always and will always be welcome.

**Comment by psteinb** [comment]
Dear @mikerenfro - thank you for recognising my work. These words mean a lot to me.

**Pull request merged**
